server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: capra-account
          uri: lb://capra-account
          predicates:
            - Path=/capra-account/**
          filters:
            - StripPrefix=1
        - id: capra-auth
          uri: lb://capra-auth
          predicates:
            - Path=/capra-auth/**
          filters:
            - StripPrefix=1
        - id: capra-article
          uri: lb://capra-article
          predicates:
            - Path=/capra-article/**
          filters:
            - StripPrefix=1

security:
  ignore:
    urls:
      - "/capra-auth/auth/register"
      - "/capra-auth/auth/login"